In [1]:
import pandas as pd
df = pd.read_csv('https://drive.google.com/uc?id=15RfMD9lNkpS3cVN7j3_dsJKZ8_5RJG5z')
df.head()

date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000

In [2]:
import tensorflow as tf


def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    series = tf.expand_dims(series, axis=-1)
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size + 1, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size + 1))
    ds = ds.shuffle(shuffle_buffer)
    ds = ds.map(lambda w: (w[:-1], w[-1:]))
    return ds.batch(batch_size).prefetch(1)

In [3]:
dates = df['date'].values
temp  = df['meantemp'].values

In [4]:
train_set = windowed_dataset(temp, window_size=2, batch_size=3, shuffle_buffer=1000)

In [5]:
for data in train_set:
  print(data)
  break

(<tf.Tensor: shape=(3, 2, 1), dtype=float64, numpy=
array([[[15.125     ],
        [15.25      ]],

       [[18.85714286],
        [16.57142857]],

       [[25.75      ],
        [25.25      ]]])>, <tf.Tensor: shape=(3, 1, 1), dtype=float64, numpy=
array([[[15.125]],

       [[17.75 ]],

       [[25.5  ]]])>)
